export const SHOW_LEFT_MENU = 'VIEW_SHOW_LEFT_MENU'
export const HIDE_LEFT_MENU = 'VIEW_HIDE_LEFT_MENU'
export const SHOW_MAIN_LOADER = 'VIEW_SHOW_MAIN_LOADER'
export const HIDE_MAIN_LOADER = 'VIEW_HIDE_MAIN_LOADER'
